#!/usr/bin/env bash
# Backlog triage actions — 2026-09-17
#
# Generated by a triage pass over all 150 open issues. Every closure below is
# backed by docs/devel/ROADMAP.md (the source of truth per CLAUDE.md) or by the
# tree; the evidence is quoted in each issue comment.
#
# NOT RUN by the session that produced it: the auto-mode classifier blocks
# external system writes (gh issue comment/close/edit, gh api -X PUT), and the
# fixall skill's allowed-tools is `Bash(git *)` only. Rationale for every action
# is in 2026-09-17-backlog-triage.md next to this file.
#
# Review, then:  bash backlog-triage-2026-09-17.sh
# Every step is independent; comment out anything you disagree with.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
W="$(mktemp -d)"
trap 'rm -rf "$W"' EXIT

say() { printf '\n=== %s ===\n' "$*"; }

# ---------------------------------------------------------------------------
# 1. Close as SHIPPED  (ROADMAP-backed)
# ---------------------------------------------------------------------------

cat > "$W/227.md" <<'EOF'
Closing as **shipped**. Verified against `docs/devel/ROADMAP.md` (source of truth per CLAUDE.md) and the tree:

- **Linux Firecracker** — ROADMAP Phase 4: `[x] Linux Firecracker micro-VM backend (SandboxBackendKind::FirecrackerVm) — SLICE 1 (2026-06-27, PR #364)`.
- **macOS Apple `container`** — ROADMAP Phase 1: `[x] macOS Apple container micro-VM backend — 2026-05-21`.
- Both are operator-selectable via `KASTELLAN_<WORKER>_USE_MICROVM=1` (e.g. `KASTELLAN_PYTHON_EXEC_USE_MICROVM=1`), documented in CLAUDE.md and dispatched in `core/src/broker/spawn.rs`.

The ROADMAP line that still carried this as unchecked was a leftover duplicate of the two entries above — its text still described the work at "discovery spike … verdict COMMIT" stage. Corrected in #717.

Remaining follow-ups live on the ROADMAP sub-bullet ("curated-wheels RO dir if/when the skill catalog demands packages; planner-prompt surfacing"), not here.
EOF

cat > "$W/215.md" <<'EOF'
Closing as **shipped**. Channel-bus fan-in has been live since 2026-06-12 and repeatedly built on since:

- ROADMAP Phase 2: `[x] Channel-bus abstraction (build first) — 2026-06-12`, `[x] Matrix inbound — 2026-06-20`, `[x] Channel bring-up is supervised, not one-shot — 2026-08-04`.
- `core/src/channel/bus.rs` + `core/src/channel/ingest.rs` are the fan-in chokepoint; `bus::handle_inbound` is where peer authorization happens for every channel family.
- Channel messages becoming core tasks is now so thoroughly shipped that #701/#709 was about giving those tasks *conversational continuity* across turns.

Bus unification across the per-family instances is tracked separately as #497.
EOF

cat > "$W/216.md" <<'EOF'
Closing as **shipped**. ROADMAP Phase 2 records `[x] DM pairing flow: — 2026-06-12`, and the operator surface is in the tree at `core/src/bin/kastellan-cli/pair.rs`:

- `pair issue` mints a **single-use, short-lived** pairing code; only its SHA-256 is stored (`pairing_codes`), plaintext printed once for out-of-band handoff.
- `pair issue-token` creates a pairing with a long-lived shared secret for channels where sender identity is spoofable (email) — a separate subcommand rather than a flag, deliberately.
- `pair list` / `pair revoke` give the audited, revocable half.
- Migration 0018 REVOKEs INSERT on `pairing_codes` and UPDATE on `pairings` from the runtime role, so minting and revoking are operator-only actions the daemon cannot perform.

**Scope note:** the title's *"TOTP/HOTP + WebAuthn"* was not implemented, and on review that is the right outcome rather than a gap. The shipped design meets the same intent by different means — a single-use, hash-stored, out-of-band code makes a rotating OTP redundant, and the forgeable-static-allowlist failure mode the issue warned about is what `issue-token` plus the DMARC+token gate actually addresses. If WebAuthn is wanted later for browser/CLI pairings specifically, that deserves its own issue with its own justification.
EOF

say "closing shipped: #227 #215 #216"
for n in 227 215 216; do
  gh issue comment "$n" --body-file "$W/$n.md"
  gh issue close "$n" --reason completed
done

# ---------------------------------------------------------------------------
# 2. Close as REJECTED / SUPERSEDED  (ROADMAP-backed)
# ---------------------------------------------------------------------------

cat > "$W/214.md" <<'EOF'
Closing as **rejected**, per the project's own decision recorded in `docs/devel/ROADMAP.md` Phase 2:

> `- [ ] ~~Telegram inbound adapter (grammers, Rust)~~ — **rejected as primary 2026-06-12** (no bot E2E, centralized, ban risk). Could return later as an additional Channel impl if a need arises.`

The decision is three months old; the issue just never mirrored it. Matrix is the primary inbound channel, with gated email as the fallback. If Telegram returns it will be as an additional `Channel` impl and deserves a fresh issue stating the need.
EOF

cat > "$W/219.md" <<'EOF'
Closing as **rejected**, per `docs/devel/ROADMAP.md` Phase 3, which strikes this through inline:

> `(~~Telegram/Signal outbound~~ rejected as primary — see Phase 2 note.)`

Matrix outbound over the E2E `MatrixChannel` is the primary outbound path (decision 2026-06-12, slice #4). SMTP outbound as the low-trust fallback is tracked separately as #220 (email-channel slice 2). Same footnote as #214: if Signal returns, it needs a fresh issue with a stated need.
EOF

cat > "$W/213.md" <<'EOF'
Closing as **superseded**. `docs/devel/ROADMAP.md` Phase 2 says so explicitly, in the email-inbound entry:

> **Supersedes the original "IMAP inbound worker" framing:** localmail now exists and already ingests the mail over IMAP, so the channel polls its `/v1` subscription instead of speaking IMAP itself — no IMAP crate to sandbox, no mail credentials in a kastellan jail, and it reuses the force-routed egress path (private netns + 1:1 sidecar) that #491/#492 built out.

Confirmed in the tree: `workers/email-in/src/client.rs` is a *"localmail REST client for the email channel's inbound half"*, and `main.rs` documents the worker as polling a localmail subscription. Nothing in kastellan speaks IMAP, by design.

Slice 1 merged 2026-07-31 (`bf8e850b`, PR #496). Remaining email-channel work is slice 2 (SMTP outbound, #220) and slice 3 (deploy + live tier).
EOF

say "closing rejected/superseded: #214 #219 #213"
for n in 214 219 213; do
  gh issue comment "$n" --body-file "$W/$n.md"
  gh issue close "$n" --reason "not planned"
done

# ---------------------------------------------------------------------------
# 3. Close the six stale roadmap epic mirrors (#203-#208)
# ---------------------------------------------------------------------------

cat > "$W/epic.md" <<'EOF'
Closing this epic as **unmaintainable by construction**.

Its own body states the trade it was built on:

> Source of truth remains the ROADMAP; this mirror exists so the work shows up on the GitHub Project board.

That mirror was never synced in the three months since, and it has now drifted far enough to actively mislead:

1. **Every ROADMAP link points at `github.com/hherb/hhagent/…`** — the pre-rename URL. These epics were filed 2026-06-08; the project was renamed hhagent → kastellan on 2026-06-10, two days later.
2. **The status text is wrong.** Phase 3 lists the egress proxy as pending (shipped 2026-06-10, `df51c5c`); Phase 4 says "All items pending" while python-exec and both micro-VM backends shipped; Phase 2's channel-bus fan-in shipped 2026-06-12.
3. **The children have drifted independently** — #213 is superseded, #214/#219 were rejected on 2026-06-12, #215/#216/#227 shipped. None of it reached the epic.

A hand-synced mirror of a well-maintained file is debt with no offsetting benefit: `docs/devel/ROADMAP.md` is current, is read at the start of every session per CLAUDE.md, and carries far more context than these ever did. Individual work items still get their own issues as they become actionable — that part is working, as the steady close rate on #661–#701 shows.

Closed as part of a full backlog triage on 2026-09-17.
EOF

say "closing epics: #203 #204 #205 #206 #207 #208"
for n in 203 204 205 206 207 208; do
  gh issue comment "$n" --body-file "$W/epic.md"
  gh issue close "$n" --reason "not planned"
done

# ---------------------------------------------------------------------------
# 4. Re-scope #237 (partially shipped) — comment only, stays open
# ---------------------------------------------------------------------------

cat > "$W/237.md" <<'EOF'
**Triage 2026-09-17 — narrowing this to what is actually left.** Two of the three legs are done or deliberately deferred; the macOS leg is the real remainder.

| Leg | State |
|---|---|
| `cargo clippy -- -D warnings` | **Done.** `.github/workflows/linux-check.yml` runs `cargo clippy --workspace --all-targets --locked -- -D warnings`. |
| `cargo test` | **Partly done, deliberately.** Hermetic per-crate suites run in CI (tests-common, mail, prelude, shell-exec, python-exec); the full `cargo test --workspace` stays operator/DGX-driven, as the workflow comments explain. |
| `cargo fmt --check` | **Deferred, deliberately.** CLAUDE.md: *"There's no rustfmt config yet; keep formatting consistent with what's already in the tree."* Adding the gate means first adopting a config and reformatting the tree — a separate decision, not a CI chore. |
| **macOS** | **Absent entirely.** All six runners across all three workflows are `ubuntu-latest`. |

So the remaining scope is **the macOS leg**, and it matters more than the other two: CLAUDE.md makes *"Cross-platform: Linux + macOS first-class"* a hard constraint, and the memory note *"Mac compiles ZERO systemd_user tests"* is the mirror-image hazard — a Mac-green run can be missing the test that pins a Linux fix, and today nothing checks the macOS direction at all.

Worth pairing with #655: until required status checks exist, adding a macOS job makes it advisory anyway.
EOF

say "re-scoping #237 (stays open)"
gh issue comment 237 --body-file "$W/237.md"

# ---------------------------------------------------------------------------
# 5. Retitle the three unfindable guard issues
# ---------------------------------------------------------------------------

say "retitling #609 #610 #611"
gh issue edit 609 --title "guard tier: an unreachable /props is fatal with no retry, so a late guard backend crash-loops the whole daemon"
gh issue edit 610 --title "guard audit: a NULL guard sub-object conflates deliberate opt-out, regression, and unconfigured host"
gh issue edit 611 --title "guard boot report: report_guard_tier's configured branch is entirely uncovered, including the fail-open warn!"

# ---------------------------------------------------------------------------
# 6. Cross-link the pairs that share a root cause
# ---------------------------------------------------------------------------

cat > "$W/673.md" <<'EOF'
**Triage 2026-09-17:** this and #674 are two halves of one incident and are best fixed together.

The DGX localmail session token (`TOKEN_TTL_DAYS = 30`, minted 2026-07-31) expired 2026-08-30. #674 is why *nothing noticed*; this issue is why, once it did surface, it surfaced as the **wrong diagnosis** — five days later, as a user-visible wrong answer, because `POLICY_DENIED` made "your credential is bad" indistinguishable from "kastellan refused this on policy grounds".

Fixing only the error code leaves the silent 30-day window; fixing only the expiry leaves the next upstream 401 misattributed. One change, two properties.
EOF

cat > "$W/674.md" <<'EOF'
**Triage 2026-09-17:** see #673 — same incident, other half. #673 is the misattribution (`POLICY_DENIED` for an upstream 401/403); this is the non-detection. Recommend fixing together.
EOF

cat > "$W/696.md" <<'EOF'
**Triage 2026-09-17:** same shape as #591 (the char-boundary truncation walk hand-written in five places) — one helper, copied rather than shared. Worth one dedup pass covering both rather than two separate PRs.

The #591 note that *"its correct test exists in only one place"* is the reason this class matters here: the copies do not share the copy's tests, so they do not share its fixes either.
EOF

say "cross-linking #673<->#674 and #696<->#591"
gh issue comment 673 --body-file "$W/673.md"
gh issue comment 674 --body-file "$W/674.md"
gh issue comment 696 --body-file "$W/696.md"

# ---------------------------------------------------------------------------
# 7. #655 — require status checks on main
#
# SAFE: linux-check.yml triggers on `pull_request:` with NO paths filter, so all
# three jobs report on every PR. A required check therefore cannot deadlock a
# docs-only PR. (The workflow comments even note python-lock-check deliberately
# does not need a `paths:` filter.)
#
# strict_required_status_checks_policy=false => does NOT force branch-up-to-date
# before merge, which would serialize merges for no safety gain here.
# ---------------------------------------------------------------------------

say "#655: adding required_status_checks to ruleset protect_main"
gh api repos/hherb/kastellan/rulesets/16475311 > "$W/ruleset.json"

python3 - "$W/ruleset.json" "$W/ruleset-new.json" <<'PYEOF'
import json, sys
src, dst = sys.argv[1], sys.argv[2]
rs = json.load(open(src))
rules = [r for r in rs.get('rules', []) if r.get('type') != 'required_status_checks']
rules.append({
    "type": "required_status_checks",
    "parameters": {
        "strict_required_status_checks_policy": False,
        "required_status_checks": [
            {"context": "cargo check + clippy (linux)"},
            {"context": "uv lock --check (gliner-relex)"},
            {"context": "cargo check + clippy (matrix worker, live-matrix)"},
        ],
    },
})
payload = {
    "name": rs["name"],
    "target": rs.get("target", "branch"),
    "enforcement": rs["enforcement"],
    "conditions": rs.get("conditions", {}),
    "rules": rules,
}
if rs.get("bypass_actors"):
    payload["bypass_actors"] = rs["bypass_actors"]
json.dump(payload, open(dst, "w"), indent=2)
print("rules now:", ", ".join(r["type"] for r in rules))
PYEOF

gh api -X PUT repos/hherb/kastellan/rulesets/16475311 --input "$W/ruleset-new.json" >/dev/null
echo "ruleset updated; verifying:"
gh api repos/hherb/kastellan/rulesets/16475311 \
  | python3 -c 'import json,sys; [print("  RULE:", r["type"]) for r in json.load(sys.stdin)["rules"]]'

cat > "$W/655.md" <<'EOF'
**Fixed 2026-09-17.** The `protect_main` ruleset (16475311) now carries a `required_status_checks` rule alongside `deletion` and `non_fast_forward`, requiring:

- `cargo check + clippy (linux)`
- `uv lock --check (gliner-relex)`
- `cargo check + clippy (matrix worker, live-matrix)`

`strict_required_status_checks_policy` is **false** deliberately — requiring branch-up-to-date before merge would serialize every merge behind a re-run for no safety gain on a repo this size.

**Why this was safe to turn on:** `linux-check.yml` triggers on `pull_request:` with **no `paths` filter**, so all three jobs report on every PR. A required check that never reports would otherwise deadlock docs-only PRs — that hazard does not exist here.

This was the cheapest high-value item in the backlog: until now every CI job was advisory, which made the whole false-green-gate cluster (#714, #664, #622, #691) moot — a gate that cannot block a merge is a notification.
EOF
gh issue comment 655 --body-file "$W/655.md"
gh issue close 655 --reason completed

say "done"
echo "Closed: #227 #215 #216 #214 #219 #213 #203-#208 #655  (12 issues)"
echo "Commented/re-scoped: #237 #673 #674 #696"
echo "Retitled: #609 #610 #611"
